### ISSUE TITLE
Switches stopped working after upgrading to HA 2023.4.1

### ISSUE THREAD

**Issue by gralin** [jpcornil-git/HA-mcp23017#18] opened 2023-04-07 07:44 UTC
I noticed that my switches (MCP23017 outputs) stopped working. Binary sensors (MCP23017 inputs) still work.
Here is the log: [home-assistant.log](https://github.com/jpcornil-git/HA-mcp23017/files/11176981/home-assistant.log)

```
2023-04-07 09:14:51.570 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 0x24:pin 0 ('Output.01':switch) for mcp23017
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/mcp23017/__init__.py", line 110, in async_unload_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mcp23017/__init__.py", line 323, in unregister_entity
    entity.unsubscribe_update_listener()
AttributeError: 'NoneType' object has no attribute 'unsubscribe_update_listener'
```

My config looks like this: [config.txt](https://github.com/jpcornil-git/HA-mcp23017/files/11177020/config.txt)

**Comment by jpcornil-git** [comment] 2023-04-07 12:52
I just tried this integration with 2023.4.1 (configflow and configuration.yaml) and I don't have any issues.

In your log, there are a lot of errors like this one
```sh
2023-04-07 09:14:52.625 ERROR (MainThread) [homeassistant.components.switch] Platform mcp23017 does not generate unique IDs. ID mcp23017-0x24-0x00 already exists - ignoring switch.output_01
```
=> it looks like for some reasons entries can't be removed and prevent initialisation of new ones.

Could you try the following:

1. comment out mcp23017 switch integrations from your configuration.yaml file and restart HA
2. integrations should still be there (configurations from yaml are converted as if they were created using configflow -> "sticky")
3. remove these integrations from HA and restart HA
4. this time they should be gone
5. uncomment mcp23017 switch integrations  and restart HA

As an alternative for steps 2-4 and after step 1, you could also edit (after a backup) the .storage/core.entity_registry file directly (look for mcp23017) and remove all corresponding entries at once (and eventually look for abnomalies/duplicates/... as well) 

PS: in your config.txt I don't see any binary_sensor: or switch: statement before -platform but I guess they were just not copied

**Comment by gralin** [comment] 2023-04-07 16:38
Thank you for your suggestions @jpcornil-git. I've commented out everything related to this integration in the configuration.yaml, removed manually the entities and confirmed after restart that the system no longer has any mcp23017 entities. After that, I have uncommented the entries in configuration.yaml, restarted HA and everything started working. But then I restarted it again, and the same problem occurs as before.

It feels like to me like some race condition, because it's undeterministic. See below logs

Restart 1 - [1.log](https://github.com/jpcornil-git/HA-mcp23017/files/11180175/1.log) - only switch.output_01 is available
Restart 2 - [2.log](https://github.com/jpcornil-git/HA-mcp23017/files/11180179/2.log) - only switch.output_02 is available
Restart 3 - [3.log](https://github.com/jpcornil-git/HA-mcp23017/files/11180181/3.log) - all outputs are available

When the outputs are not available, I can restore them one by one by clicking 'reload' on the integration.

It also feels connected to the problem I described in #13 but for which I never got to provide any conrete feedback.

> PS: in your config.txt I don't see any binary_sensor: or switch: statement before -platform but I guess they were just not copied

Yes, exactly. I have them splitted into separate files and that's why when I copied them I forgot to add the platform.

**Comment by jpcornil-git** [comment] 2023-04-07 17:21
Thanks for the tests.

It looks like a race condition between removal of the cached configuration and the load of the one from configuration.yaml.
I guess that if you comment all of them in configuration.yaml, they always load correctly ?

I'll have a look at possible integration/HA causes later today as well

**Comment by gralin** [comment] 2023-04-07 18:21
Yes, exactly, if comment out things in congratulation.json, everything is ok after restart.

**Comment by jpcornil-git** [comment] 2023-04-08 22:07
I'm now able to reproduce your issue after restarting two times or more.

It is related to the way HA initializes entities from configuration.yaml and from store (core.config_entries in .storage)
Up to now it seems that the latter was able to complete before the former (yaml overloading store) but what I see here is that when both exists, they start in parallel and in random order and therefore affect each other's (new one trying to unload the older one which is still initialiing) ...

I guess it is related to "the future of yaml for integration" (deprecated in favor of UI/config flow), see https://www.home-assistant.io/blog/2020/04/14/the-future-of-yaml/

Existing yaml for this integration can be imported as before but once completed it should be removed/commented out of configuration.yaml and modified using the UI moving forward.

I'll have another look at this in the next few days ...

**Comment by jpcornil-git** [comment] 2023-04-09 17:46
I just checked in a possible workaround (I see that config setup from store starts first in a burst, the yaml config is now delayed as long as there is one such setup outstanding ) => Could you give it a try and let me know how it works for you ?

**Comment by darmach** [comment] 2023-04-11 22:57
I stumbled upon the same issue - unlucky enough I'm unable to any of the window shutters :D
Does the workaround work, and can you release?

**Comment by jpcornil-git** [comment] 2023-04-12 06:36
Thanks for the feedback @darmach , I see a thumb up from @gralin and assume that it works for him as well
=> I'll move beta to a new release later today and try to extend life/support for both yaml and config flow once more time :-)

**Comment by gralin** [comment] 2023-04-12 10:50
@jpcornil-git yes, I can also confirm it seems to work! I did several reboots and still no issues. It also seems to fix #13 as my lights created from outpus are preserved 😊 I know that config flow should be preferred over yaml, but in my case, creating 48 inputs and 32 outpus would take some time with config flow 😅

**Comment by jpcornil-git** [comment] 2023-04-12 14:20
Thanks for the confirmation @gralin; agree as well that config flow is not practical when # of devices if high and therefore a yaml import option should always remain available. Once imported/for incremental changes configflow works OK and is more user friendly.

**Comment by jpcornil-git** [comment] 2023-04-12 17:51
Just made a new release implementing this/closing the issue

**Closed by jpcornil-git** 2023-04-12 17:51 UTC

**Comment by gralin** [comment] 2023-04-12 18:03
@jpcornil-git than you for your support! Do you have buymeacoffee or any similar page?

**Comment by jpcornil-git** [comment] 2023-04-12 19:55
No but always happy to help and a thank you is great :-)
